// AUTO-GENERATED STRICT 1:1 LEGACY DATABASE SEED
// Extracted from database/ & WordPress XML export with exact taxonomy & image bindings

import type { AdminPropertyPost, CrmLead } from "./admin-store";
import type { BlogPost, MediaAsset } from "./types";
import { ALL_PROPERTY_MEDIA_ASSETS } from "./media-seed";

export const SEED_PROPERTIES_DATA: AdminPropertyPost[] = [
  {
    id: "prop-31207",
    title: "Commercial Property At North Main St Waterbury",
    slug: "commercial-property-at-north-main-st-waterbury",
    description:
      "Very nice property that has many uses, the building comes with 12 acres of land , has a church, rectory, and it’s free standing. Buildings can be used for weddings, parties, church etc. It has an industrial kitchen conference room, a main area and many private rooms. The area is zoned residential for single family homes",
    author: "Majeed Sharif",
    category: "Commercial",
    propertyType: "Commercial",
    tags: ["commercial", "retail", "office", "waterbury", "investment", "featured"],
    status: "Published",
    listingType: "commercial",
    propertyStatus: "for_sale",
    priceLabel: "Price on Call",
    comments: 0,
    date: "2025-05-26",
    price: 0,
    beds: 0,
    baths: 2,
    sqft: 8500,
    lotSize: "12 Acres",
    garageSpaces: 20,
    yearBuilt: 1985,
    address: "North Main St Waterbury",
    city: "Waterbury",
    state: "CT",
    zip: "06704",
    latitude: 41.5682,
    longitude: -73.0392,
    isFeatured: true,
    image: "/wp-content/uploads/2025/05/IMG_4535.jpg",
    images: ["/wp-content/uploads/2025/05/IMG_4535.jpg"],
    features: [
      "12 Acres of Expansive Land",
      "Free Standing Church & Rectory Buildings",
      "Industrial Kitchen & Conference Room",
      "Large Main Area and Multiple Private Rooms",
      "Zoned Residential for Single Family Homes",
      "Ideal for Weddings, Parties, Church & Events",
      "North Main St Waterbury Frontage",
      "Ample On-Site Parking",
    ],
  },
  {
    id: "prop-31073",
    title: "Single family 4 bedrooms 3 baths",
    slug: "single-family-4-bedrooms-3-baths",
    description:
      "Well-appointed colonial single-family home located in East Hartford, CT. Offering 4 spacious bedrooms, 3 full bathrooms, updated eat-in kitchen with stainless appliances, hardwood flooring throughout, private backyard patio, and attached garage. Convenient to major transit corridors, parks, and regional employers.",
    author: "Majeed Sharif",
    category: "Houses",
    propertyType: "Houses",
    tags: ["residential", "houses", "east-hartford", "single-family"],
    status: "Published",
    listingType: "buy",
    propertyStatus: "for_sale",
    priceLabel: "Price on Call",
    comments: 0,
    date: "2025-05-29",
    price: 0,
    beds: 4,
    baths: 3,
    sqft: 2280,
    lotSize: "0.42 Acres",
    garageSpaces: 2,
    yearBuilt: 1998,
    address: "East Hartford",
    city: "East Hartford",
    state: "CT",
    zip: "06108",
    latitude: 41.7634,
    longitude: -72.6131,
    isFeatured: false,
    image: "/wp-content/uploads/2025/05/16-thendara.jpg",
    images: ["/wp-content/uploads/2025/05/16-thendara.jpg"],
    features: [
      "4 Generous Bedrooms",
      "3 Full Updated Bathrooms",
      "Stainless Steel Kitchen Package",
      "Hardwood Flooring",
      "Attached Garage",
      "Private Backyard with Patio",
      "Energy Efficient Windows",
      "Central Heat & Air",
    ],
  },
  {
    id: "prop-31948",
    title: "Waterbury Connecticut",
    slug: "waterbury-connecticut",
    description:
      "Spectacular private residential estate located along the Southington and Waterbury town border. Featuring manicured grounds, custom architectural millwork, spacious two-car attached garage, expansive primary suite with walk-in dressing lounge, open-concept living area, central air conditioning, and room for a private pool or equestrian amenities.",
    author: "Majeed Sharif",
    category: "Residential",
    propertyType: "Residential",
    tags: ["residential", "estate", "southington", "waterbury", "featured", "for-sale"],
    status: "Published",
    listingType: "buy",
    propertyStatus: "for_sale",
    priceLabel: "Price on call",
    comments: 0,
    date: "2025-05-30",
    price: 0,
    beds: 3,
    baths: 2,
    sqft: 2400,
    lotSize: "2.1 Acres",
    garageSpaces: 2,
    yearBuilt: 2014,
    address: "Southington Ct",
    city: "Southington Ct",
    state: "CT",
    zip: "06489",
    latitude: 41.5995,
    longitude: -72.8781,
    isFeatured: true,
    image: "/wp-content/uploads/2025/05/image-16.png",
    images: ["/wp-content/uploads/2025/05/image-16.png"],
    features: [
      "2.10 Acres Private Manicured Grounds",
      "Custom Chef Kitchen & Island",
      "Primary Suite with Spa Bath",
      "Hardwood Floors Throughout",
      "Two-Car Attached Garage",
      "Multi-Zone Central Air",
      "Expansive Outdoor Entertainment Deck",
      "Finished Walk-Out Lower Level",
    ],
  },
  {
    id: "prop-31965",
    title: "Split Level Home",
    slug: "split-level-home-waterbury",
    description:
      "Nestled in a desirable location of Waterbury Ct, this split-level home showcases four bedrooms, 2.5 bathrooms, two kitchens, and hardwood floors throughout. The property also features room above the patio with separate entrance, granite countertops, and stainless steel appliances. Outside you will find an above ground swimming pool, and a beautifully landscaped yard with patio, deck, and paver driveway.",
    author: "Majeed Sharif",
    category: "Houses",
    propertyType: "Houses",
    tags: ["residential", "split-level", "waterbury", "sold", "single-family"],
    status: "Published",
    listingType: "buy",
    propertyStatus: "sold",
    priceLabel: "Sold",
    comments: 0,
    date: "2025-07-18",
    price: 425000,
    beds: 4,
    baths: 2.5,
    sqft: 2100,
    lotSize: "0.35 Acres",
    garageSpaces: 2,
    yearBuilt: 1985,
    address: "115 Kendall Dr",
    city: "Waterbury",
    state: "Connecticut",
    zip: "06708",
    latitude: 41.564,
    longitude: -73.045,
    isFeatured: true,
    image: "/wp-content/uploads/2025/06/115-KENDALL-PIC-1.webp",
    images: [
      "/wp-content/uploads/2025/06/115-KENDALL-PIC-1.webp",
      "/wp-content/uploads/2025/06/115-KENDALL-PIC.webp",
    ],
    features: [
      "Custom Paver Driveway & Landscaped Yard",
      "4 Spacious Bedrooms & 2.5 Bathrooms",
      "Hardwood Floors Throughout",
      "Two Fully Equipped Kitchens",
      "Granite Countertops & Stainless Steel Appliances",
      "Room Above Patio with Separate Entrance",
      "Above-Ground Swimming Pool & Sun Deck",
      "Private Backyard Patio for Entertaining",
      "Attached Garage Parking",
    ],
  },
  {
    id: "prop-32097",
    title: "270 New Britain Rd Unit 20",
    slug: "270-new-britain-rd-unit-20-berlin-ct",
    description:
      "Luxury turnkey townhome condominium at 270 New Britain Rd Unit 20, Berlin, CT 06037. Constructed in 2021, this modern 1,400 square foot residence features 2 generous bedroom suites, 2.5 designer bathrooms, high-efficiency mechanical systems, open-concept kitchen with premium appliances, and a private attached garage. Last transacted at $440,000 ($314/sqft).",
    author: "Majeed Sharif",
    category: "Condos",
    propertyType: "Condos",
    tags: ["condos", "townhouse", "berlin", "sold", "turnkey"],
    status: "Published",
    listingType: "buy",
    propertyStatus: "sold",
    priceLabel: "Sold",
    comments: 0,
    date: "2026-01-25",
    price: 440000,
    beds: 2,
    baths: 2.5,
    sqft: 1400,
    lotSize: "Condominium",
    garageSpaces: 1,
    yearBuilt: 2021,
    address: "270 New Britain Rd Unit 20",
    city: "Berlin",
    state: "Connecticut",
    zip: "06037",
    latitude: 41.621,
    longitude: -72.776,
    isFeatured: true,
    image: "/wp-content/uploads/2026/01/1-2.png",
    images: [
      "/wp-content/uploads/2026/01/1-2.png",
      "/wp-content/uploads/2026/01/2-2.png",
      "/wp-content/uploads/2026/01/3-2.png",
      "/wp-content/uploads/2026/01/4-2.png",
      "/wp-content/uploads/2026/01/5-2.png",
      "/wp-content/uploads/2026/01/6-1.png",
      "/wp-content/uploads/2026/01/7-1.png",
      "/wp-content/uploads/2026/01/8-1.png",
      "/wp-content/uploads/2026/01/9-1.png",
      "/wp-content/uploads/2026/01/10-1.png",
      "/wp-content/uploads/2026/01/11-1.png",
      "/wp-content/uploads/2026/01/12-1.png",
      "/wp-content/uploads/2026/01/13-1.png",
      "/wp-content/uploads/2026/01/14-1.png",
      "/wp-content/uploads/2026/01/15-1.png",
    ],
    features: [
      "Modern 2021 Turnkey Construction",
      "2 Bedroom Suites & 2.5 Designer Baths",
      "1,400 Sq Ft Open-Concept Floor Plan",
      "Designer Kitchen with Quartz Island",
      "Private Attached Garage & Dedicated Driveway",
      "High-Efficiency Heating & Central Air",
      "Low-Maintenance Condominium Living",
      "Prime Central Connecticut Location",
    ],
  },
  {
    id: "prop-32110",
    title: "4BR Colonial with Solar Panels",
    slug: "4br-colonial-with-solar-panels-waterbury-ct",
    description:
      "Your Dream Home is Here! Don't Miss This!\n📍 Waterbury, Connecticut\n🛏️ 4 Bedrooms | 🛁 2.5 Bathrooms\n💰 Asking: $349,000\n\nHighlights:\n✅ Spacious 4BR colonial - perfect for family living\n✅ Energy-efficient with Solar Panels = Lower electric bills!\n✅ Beautiful green lawn & mature landscaping\n✅ Bright interior with large windows\n✅ Move-in ready in a quiet, established neighborhood\n\nThis charming 2-story home offers space, comfort, and savings! Ideal for first-time buyers, growing families, or investors.\n\nHomes like this in Waterbury at this price DON'T LAST!\n📞 Call/DM Now for a private showing!\nSHARIF REALTY GROUP LLC\n📧 sharifrealty19@gmail.com\n📞 +1 (203) 802-8099\nServing CT & MA",
    author: "Majeed Sharif",
    category: "Houses",
    propertyType: "Houses",
    tags: [
      "WaterburyCT",
      "ConnecticutRealEstate",
      "HouseForSale",
      "CTHomes",
      "HomeForSale",
      "JustListed",
      "4BedroomHome",
      "SharifRealty",
      "CTRealEstate",
    ],
    status: "Published",
    listingType: "buy",
    propertyStatus: "for_sale",
    priceLabel: "$349,000",
    comments: 0,
    date: "2026-09-16",
    price: 349000,
    beds: 4,
    baths: 2.5,
    sqft: 2200,
    lotSize: "0.28 Acres",
    garageSpaces: 1,
    yearBuilt: 1980,
    address: "Waterbury",
    city: "Waterbury",
    state: "Connecticut",
    zip: "06708",
    latitude: 41.5582,
    longitude: -73.0515,
    isFeatured: true,
    image: "/wp-content/uploads/waterbury-colonial-solar.jpg",
    images: ["/wp-content/uploads/waterbury-colonial-solar.jpg"],
    galleryImages: ["/wp-content/uploads/waterbury-colonial-solar.jpg"],
    features: [
      "Spacious 4BR colonial - perfect for family living",
      "Energy-efficient with Solar Panels = Lower electric bills!",
      "Beautiful green lawn & mature landscaping",
      "Bright interior with large windows",
      "Move-in ready in a quiet, established neighborhood",
      "Charming 2-story home offers space, comfort, and savings",
      "Ideal for first-time buyers, growing families, or investors",
      "Asking: $349,000",
    ],
  },
  {
    id: "prop-32115",
    title: "110 White Birch Dr - Bunker Hill Raised Ranch",
    slug: "110-white-birch-dr-waterbury-ct",
    description:
      "🏡 UNDER CONTRACT IN WATERBURY, CT! 🏡\n\nExceptional Bunker Hill Raised Ranch Retreat!\n📍 110 White Birch Dr, Waterbury, Connecticut\n🛏️ 4 Bedrooms | 🛁 2.5 Bathrooms | 📐 2,488 Sq Ft\n🌳 0.95-Acre Secluded Private Lot\n💰 Asking: Price on Call (Now Under Contract)\n\nProperty Highlights:\n✅ Spacious Raised Ranch nestled in the highly sought-after Bunker Hill neighborhood\n✅ Custom architectural paver walkway flanked by elegant stone pillars and lanterns\n✅ High-efficiency rooftop Solar Panel system delivering substantial utility savings\n✅ Sun-drenched living room with bay window overlooking picturesque front grounds\n✅ Lower-level drive-in garage with direct interior access and walkout potential\n✅ Expansive private backyard surrounded by mature woodlands for serene outdoor living\n✅ Prime Waterbury location convenient to major commuter arteries, shopping, and dining\n\nThis stunning property is currently Under Contract. For upcoming private listings and off-market opportunities across Connecticut, connect with us today!\n\nSHARIF REALTY GROUP LLC\n📞 Direct: +1 (203) 802-8099\n📧 Email: sharifrealty19@gmail.com\nServing Connecticut & Massachusetts\nwa.me/12038028099",
    author: "Majeed Sharif",
    category: "Houses",
    propertyType: "Single Family",
    tags: [
      "WaterburyCT",
      "BunkerHill",
      "UnderContract",
      "RaisedRanch",
      "SolarPanels",
      "ConnecticutRealEstate",
      "HouseForSale",
      "CTHomes",
      "SharifRealty",
    ],
    status: "Published",
    listingType: "buy",
    propertyStatus: "pending",
    priceLabel: "Price on Call",
    comments: 0,
    date: "2026-09-16",
    price: 0,
    beds: 4,
    baths: 2.5,
    sqft: 2488,
    lotSize: "0.95 Acres",
    garageSpaces: 1,
    yearBuilt: 1979,
    address: "110 White Birch Dr",
    city: "Waterbury",
    state: "Connecticut",
    zip: "06708",
    latitude: 41.559,
    longitude: -73.072,
    isFeatured: true,
    image: "/wp-content/uploads/waterbury-split-level-110.jpg",
    images: ["/wp-content/uploads/waterbury-split-level-110.jpg"],
    galleryImages: ["/wp-content/uploads/waterbury-split-level-110.jpg"],
    features: [
      "Sought-After Bunker Hill Neighborhood",
      "Custom Paver Walkway with Stone Lamp Pillars",
      "High-Efficiency Rooftop Solar Panels",
      "Spacious 2,488 Sq Ft Raised Ranch Design",
      "0.95-Acre Secluded Wooded Grounds",
      "Bay Window & Sun-Drenched Interiors",
      "Lower-Level Garage with Direct Access",
      "Under Contract - Price on Call",
    ],
  },
  {
    id: "prop-32120",
    title: "Another Property Sold - 3 Bedrooms 1.5 Bath Waterbury CT",
    slug: "another-property-sold-3-bedrooms-1-5-bath-waterbury-ct",
    description:
      "Another property successfully sold by Sharif Realty Group! This charming 3-bedroom, 1.5-bathroom single family home in Waterbury, Connecticut features classic Dutch Gambrel architecture, an oversized detached 2-car garage, private paved driveway, welcoming covered front porch, and manicured grounds with mature privacy hedges. Sharif Realty Group is proud to deliver another smooth transaction and successful closing for our clients. Contact us today for premier residential and commercial representation across Connecticut and Massachusetts.",
    author: "Majeed Sharif",
    category: "Houses",
    propertyType: "Houses",
    tags: [
      "WaterburyCT",
      "Sold",
      "SingleFamily",
      "Colonial",
      "ConnecticutRealEstate",
      "SharifRealty",
      "3Bedrooms",
    ],
    status: "Published",
    listingType: "buy",
    propertyStatus: "sold",
    priceLabel: "Sold",
    comments: 0,
    date: "2026-09-16",
    price: 0,
    beds: 3,
    baths: 1.5,
    sqft: 1850,
    lotSize: "0.32 Acres",
    garageSpaces: 2,
    yearBuilt: 1945,
    address: "Waterbury",
    city: "Waterbury",
    state: "Connecticut",
    zip: "06708",
    latitude: 41.562,
    longitude: -73.042,
    isFeatured: true,
    image: "/wp-content/uploads/waterbury-3bed-1halfbath-sold.jpg",
    images: ["/wp-content/uploads/waterbury-3bed-1halfbath-sold.jpg"],
    galleryImages: ["/wp-content/uploads/waterbury-3bed-1halfbath-sold.jpg"],
    features: [
      "3 Bedrooms & 1.5 Bathrooms",
      "Classic Dutch Gambrel Architecture",
      "Detached 2-Car Garage with Workshop Space",
      "Private Paved Driveway & Parking",
      "Covered Front Entry Porch with Paver Walkway",
      "Manicured Lawn & Mature Evergreen Privacy Landscaping",
      "Waterbury, CT Established Residential Setting",
      "Successfully Sold by Sharif Realty Group",
    ],
  },
  {
    id: "prop-32121",
    title: "Commercial Property 350 S Main St Cheshire CT",
    slug: "commercial-property-350-s-main-st-cheshire-ct-sold",
    description:
      "Sharif Realty Group proudly represented the buyer on the acquisition of this premier commercial property located at 350 S Main St, Cheshire, CT. Prominently positioned along Route 10 (South Main Street) in Cheshire's vibrant commercial corridor, this two-story multi-tenant professional and medical office building features high road visibility, dedicated curbside and monument tenant signage, expansive on-site paved parking, modern brick and glass architecture, and flexible commercial suites. Another landmark commercial transaction successfully closed by Sharif Realty Group!",
    author: "Majeed Sharif",
    category: "Commercial",
    propertyType: "Commercial",
    tags: [
      "CheshireCT",
      "Commercial",
      "Office",
      "Sold",
      "RepresentedBuyer",
      "SharifRealty",
      "InvestmentProperty",
      "Route10",
    ],
    status: "Published",
    listingType: "commercial",
    propertyStatus: "sold",
    priceLabel: "Sold (Represented Buyer)",
    comments: 0,
    date: "2026-09-16",
    price: 0,
    beds: 0,
    baths: 4,
    sqft: 9800,
    lotSize: "1.15 Acres",
    garageSpaces: 35,
    yearBuilt: 1988,
    address: "350 S Main St",
    city: "Cheshire",
    state: "Connecticut",
    zip: "06410",
    latitude: 41.4925,
    longitude: -72.9065,
    isFeatured: true,
    image: "/wp-content/uploads/350-south-main-cheshire-sold.jpg",
    images: ["/wp-content/uploads/350-south-main-cheshire-sold.jpg"],
    galleryImages: ["/wp-content/uploads/350-south-main-cheshire-sold.jpg"],
    features: [
      "Sharif Realty Group Represented the Buyer",
      "350 S Main St (Route 10) Prime Cheshire Commercial Corridor",
      "Multi-Tenant Professional & Medical Office Building",
      "Modern Architectural Brick & Glass Atrium Entrance",
      "Large On-Site Paved Parking Lot for Tenants & Clients",
      "Curbside Multi-Tenant Directory Signage & Mailbox Hub",
      "High Visibility & Heavy Daily Traffic Counts",
      "Successfully Closed & Sold by Sharif Realty Group",
    ],
  },
  {
    id: "prop-32122",
    title: "Commercial Property 550 North Main St Southington CT",
    slug: "commercial-property-550-north-main-st-southington-ct-sold",
    description:
      "Sharif Realty Group proudly represented the buyers on this high-performing commercial shopping and professional plaza located at 550 North Main St, Southington, Connecticut. Positioned in a vibrant commercial corridor along North Main Street (Route 10), this multi-unit commercial center features high-visibility street frontage, active retail and salon storefronts, restaurant dining, second-level executive office suites, generous customer parking, and classic New England architecture with roof dormers. Congratulations to our buyer clients on this strategic commercial investment!",
    author: "Majeed Sharif",
    category: "Commercial",
    propertyType: "Commercial",
    tags: [
      "SouthingtonCT",
      "Commercial",
      "Retail",
      "Plaza",
      "Sold",
      "RepresentedBuyers",
      "SharifRealty",
      "InvestmentProperty",
    ],
    status: "Published",
    listingType: "commercial",
    propertyStatus: "sold",
    priceLabel: "Sold (Represented Buyers)",
    comments: 0,
    date: "2026-09-16",
    price: 0,
    beds: 0,
    baths: 6,
    sqft: 14500,
    lotSize: "1.85 Acres",
    garageSpaces: 50,
    yearBuilt: 1995,
    address: "550 North Main St",
    city: "Southington",
    state: "Connecticut",
    zip: "06489",
    latitude: 41.611,
    longitude: -72.876,
    isFeatured: true,
    image: "/wp-content/uploads/550-north-main-southington-sold.jpg",
    images: ["/wp-content/uploads/550-north-main-southington-sold.jpg"],
    galleryImages: ["/wp-content/uploads/550-north-main-southington-sold.jpg"],
    features: [
      "Sharif Realty Group Represented the Buyers",
      "550 North Main St High-Traffic Southington Location",
      "Multi-Tenant Commercial & Retail Shopping Plaza",
      "Established Storefronts & Professional Office Suites",
      "Expansive Paved Parking Lot for Customers & Tenants",
      "Distinctive Colonial Architecture with Dormers",
      "Prime Investment & Commercial Asset",
      "Successfully Closed & Sold by Sharif Realty Group",
    ],
  },
];

export const SEED_BLOG_POSTS_DATA: BlogPost[] = [
  {
    id: "blog-1",
    title:
      "Off Market 4 bed 3 bath 1,724sqft 1,724 square feet 6,534sqft lot 6,534 square foot lot 102 Madera Dr, Waterbury, CT 06704 Property type Single Family Year built 1987 Last sold $369K in 2024 Price per sqft $214 Garage",
    slug: "off-market-4-bed-3-bath-1724sqft-1724-square-fe",
    excerpt:
      "102 Madera Dr, Waterbury, CT 06704 · Property type: Single Family · Year built: 1987 · Last sold: $369K in 2024 · Price per sqft: $214 · Garage",
    content:
      "<p>Exclusive off-market single family residence located in the tranquil neighborhood of <strong>102 Madera Dr, Waterbury, CT 06704</strong>.</p><p>Featuring 4 spacious bedrooms, 3 full bathrooms, and 1,724 square feet of comfortable living space situated on a 6,534 sq ft landscaped lot. Built in 1987 and last sold for $369,000 ($214/sqft), this home offers attached garage parking, ample natural light, and convenient access to local shopping, dining, and commuter routes.</p>",
    date: "January 25, 2026",
    category: "Off-Market",
    author: "Majeed",
    authorRole: "Principal Broker",
    readTime: "3 min read",
    coverImage: "/wp-content/themes/wpresidence/img/defaults/default_property_listings.jpg",
    galleryImages: [
      "/wp-content/uploads/2026/01/1-3.png",
      "/wp-content/uploads/2026/01/1-3-835x467.png",
      "/wp-content/uploads/2026/01/1-3-600x519.png",
    ],
    propertySpecs: {
      address: "102 Madera Dr, Waterbury, CT 06704",
      beds: 4,
      baths: 3,
      sqft: "1,724",
      lotSize: "6,534 sqft lot (0.15 Acres)",
      propertyType: "Single Family",
      yearBuilt: 1987,
      lastSold: "$369K in 2024",
      pricePerSqft: "$214",
      garage: "Attached Garage",
    },
    tags: ["Off-Market", "Waterbury", "Single Family", "Featured"],
    status: "Published",
    comments: 0,
    seoScore: 95,
    views: 0,
  },
  {
    id: "blog-2",
    title:
      "Off Market 2 bed 2.5 bath 1,400sqft 1,400 square feet 270 New Britain Rd Unit 20, Berlin, CT 06037 Property type Condos Year built 2021 Last sold $440K in 2024 Price per sqft $314 Garage",
    slug: "off-market-2-bed-2-5-bath-1400sqft-1400-square-",
    excerpt:
      "270 New Britain Rd Unit 20, Berlin, CT 06037 · Property type: Condos · Year built: 2021 · Last sold: $440K in 2024 · Price per sqft: $314 · Garage",
    content:
      "<p>Luxury turnkey townhome condominium at <strong>270 New Britain Rd Unit 20, Berlin, CT 06037</strong>.</p><p>Constructed in 2021, this modern 1,400 square foot residence features 2 generous bedroom suites, 2.5 designer bathrooms, high-efficiency mechanical systems, open-concept kitchen with premium appliances, and a private attached garage.</p><p>Last transacted at $440,000 ($314/sqft), this home offers the ideal maintenance-free lifestyle in central Connecticut with swift access to highways, parks, and downtown Berlin amenities.</p>",
    date: "January 25, 2026",
    category: "Off-Market",
    author: "Majeed",
    authorRole: "Principal Broker",
    readTime: "3 min read",
    coverImage: "/wp-content/themes/wpresidence/img/defaults/default_property_listings.jpg",
    galleryImages: [
      "/wp-content/uploads/2026/01/1-2.png",
      "/wp-content/uploads/2026/01/14-1.png",
      "/wp-content/uploads/2026/01/13-1.png",
      "/wp-content/uploads/2026/01/12-1.png",
      "/wp-content/uploads/2026/01/11-1.png",
      "/wp-content/uploads/2026/01/10-1.png",
      "/wp-content/uploads/2026/01/9-1.png",
      "/wp-content/uploads/2026/01/8-1.png",
      "/wp-content/uploads/2026/01/7-1.png",
      "/wp-content/uploads/2026/01/6-1.png",
      "/wp-content/uploads/2026/01/5-2.png",
      "/wp-content/uploads/2026/01/4-2.png",
      "/wp-content/uploads/2026/01/3-2.png",
      "/wp-content/uploads/2026/01/2-2.png",
    ],
    propertySpecs: {
      address: "270 New Britain Rd Unit 20, Berlin, CT 06037",
      beds: 2,
      baths: 2.5,
      sqft: "1,400",
      lotSize: "Condominium",
      propertyType: "Condos",
      yearBuilt: 2021,
      lastSold: "$440K in 2024",
      pricePerSqft: "$314",
      garage: "Attached Garage",
    },
    tags: ["Off-Market", "Berlin", "Condos", "Townhouse"],
    status: "Published",
    comments: 0,
    seoScore: 94,
    views: 0,
  },
  {
    id: "blog-3",
    title:
      "Off Market 4 bed 2.5 bath 3,239sqft 3,239 square feet 1.25acre lot 1.25 acre lot 5 Shire Way, Burlington, CT 06013 Property type Single Family Year built 2014 Last sold $770K in 2025 Price per sqft $238 Garage",
    slug: "off-market-4-bed-2-5-bath-3239sqft-3239-square-",
    excerpt:
      "5 Shire Way, Burlington, CT 06013 · Property type: Single Family · Year built: 2014 · Last sold: $770K in 2025 · Price per sqft: $238 · Garage: 3",
    content:
      "<p>Spectacular custom executive estate located at <strong>5 Shire Way, Burlington, CT 06013</strong> on an expansive 1.25-acre secluded private parcel.</p><p>Built to top standards in 2014, this 3,239 square foot masterpiece boasts 4 bedrooms, 2.5 luxury bathrooms, a grand 3-car garage, soaring ceilings, chef's kitchen with stone countertops, and extensive outdoor entertaining decks.</p><p>Last sold for $770,000 ($238/sqft) in 2025, offering unmatched tranquility, privacy, and architectural sophistication.</p>",
    date: "January 25, 2026",
    category: "Off-Market",
    author: "Majeed",
    authorRole: "Principal Broker",
    readTime: "4 min read",
    coverImage: "/wp-content/themes/wpresidence/img/defaults/default_property_listings.jpg",
    galleryImages: [
      "/wp-content/uploads/2026/01/1-1.png",
      "/wp-content/uploads/2026/01/12.png",
      "/wp-content/uploads/2026/01/13.png",
      "/wp-content/uploads/2026/01/14.png",
      "/wp-content/uploads/2026/01/15.png",
      "/wp-content/uploads/2026/01/16.png",
      "/wp-content/uploads/2026/01/17.png",
      "/wp-content/uploads/2026/01/18.png",
      "/wp-content/uploads/2026/01/19.png",
      "/wp-content/uploads/2026/01/11.png",
      "/wp-content/uploads/2026/01/10.png",
      "/wp-content/uploads/2026/01/2-1.png",
      "/wp-content/uploads/2026/01/3-1.png",
      "/wp-content/uploads/2026/01/4-1.png",
      "/wp-content/uploads/2026/01/5-1.png",
      "/wp-content/uploads/2026/01/6.png",
      "/wp-content/uploads/2026/01/7.png",
      "/wp-content/uploads/2026/01/8.png",
      "/wp-content/uploads/2026/01/9.png",
      "/wp-content/uploads/2026/01/20.png",
    ],
    propertySpecs: {
      address: "5 Shire Way, Burlington, CT 06013",
      beds: 4,
      baths: 2.5,
      sqft: "3,239",
      lotSize: "1.25 Acres (54,450 sq ft)",
      propertyType: "Single Family",
      yearBuilt: 2014,
      lastSold: "$770K in 2025",
      pricePerSqft: "$238",
      garage: "3-Car Attached Garage",
    },
    tags: ["Off-Market", "Burlington", "Luxury", "Estate"],
    status: "Published",
    comments: 0,
    seoScore: 96,
    views: 0,
  },
  {
    id: "blog-4",
    title:
      "Off Market 3 bed 3 bath 1,184sqft 1,184 square feet 7,405sqft lot 7,405 square foot lot 71 Avon Ave, Waterbury, CT 06708 Property type Single Family Year built 1960 Last sold $305K in 2025 Price per sqft",
    slug: "off-market-3-bed-3-bath-1184sqft-1184-square-fe",
    excerpt:
      "71 Avon Ave, Waterbury, CT 06708 · Property type: Single Family · Year built: 1960 · Last sold: $305K in 2025 · 7,405 sqft lot",
    content:
      "<p>Turnkey off-market home situated at <strong>71 Avon Ave, Waterbury, CT 06708</strong>.</p><p>This attractive property features 3 bedrooms, 3 full bathrooms, and 1,184 square feet of updated living space situated on a 7,405 square foot lot.</p><p>Built in 1960 with extensive modern updates and transacted for $305,000 in 2025, the property offers a private fenced backyard, attached garage, and turnkey move-in condition.</p>",
    date: "January 25, 2026",
    category: "Off-Market",
    author: "Majeed",
    authorRole: "Principal Broker",
    readTime: "3 min read",
    coverImage: "/wp-content/themes/wpresidence/img/defaults/default_property_listings.jpg",
    galleryImages: [
      "/wp-content/uploads/2026/01/1.png",
      "/wp-content/uploads/2026/01/2.png",
      "/wp-content/uploads/2026/01/3.png",
      "/wp-content/uploads/2026/01/4.png",
      "/wp-content/uploads/2026/01/5.png",
    ],
    propertySpecs: {
      address: "71 Avon Ave, Waterbury, CT 06708",
      beds: 3,
      baths: 3,
      sqft: "1,184",
      lotSize: "7,405 sq ft (0.17 Acres)",
      propertyType: "Single Family",
      yearBuilt: 1960,
      lastSold: "$305K in 2025",
      pricePerSqft: "$258",
      garage: "Attached Garage",
    },
    tags: ["Off-Market", "Waterbury", "Single Family"],
    status: "Published",
    comments: 0,
    seoScore: 92,
    views: 0,
  },
  {
    id: "blog-5",
    title: "Update!",
    slug: "update",
    excerpt: "Latest news, company updates, and market intelligence from Sharif Realty Group.",
    content:
      "<p>Sharif Realty Group continues to broaden our scope of client advisory, private property acquisitions, and off-market representations across Connecticut and Massachusetts.</p><p>Whether you are seeking exclusive commercial investment properties, prime residential estates, or tailored valuation advisement, our experienced brokerage group provides unmatched insight and discretion.</p><p>For inquiries or confidential property discussions, reach out directly to Majeed Sharif at (203) 802-8099.</p>",
    date: "January 21, 2026",
    category: "Company News",
    author: "Majeed",
    authorRole: "Principal Broker",
    readTime: "2 min read",
    coverImage: "/wp-content/themes/wpresidence/img/defaults/default_property_listings.jpg",
    tags: ["Update", "News", "Sharif Realty"],
    status: "Published",
    comments: 0,
    seoScore: 90,
    views: 0,
  },
  {
    id: "blog-6",
    title: "Latest News From NAR",
    slug: "latest-news-from-nar-2",
    excerpt: "https://www.nar.realtor/latest-news-from-nar",
    content:
      "<p>Official real estate industry news and market reports published by the National Association of Realtors (NAR).</p><p>Stay informed with the latest updates on housing market trends, mortgage interest rate developments, home sales data, and regulatory announcements shaping real estate across the nation.</p>",
    sourceUrl: "https://www.nar.realtor/latest-news-from-nar",
    date: "December 26, 2025",
    category: "Market Trends",
    author: "Majeed",
    authorRole: "Principal Broker",
    readTime: "3 min read",
    coverImage: "/wp-content/themes/wpresidence/img/defaults/default_property_listings.jpg",
    tags: ["NAR", "News", "Industry", "Market"],
    status: "Published",
    comments: 0,
    seoScore: 89,
    views: 0,
  },
  {
    id: "blog-7",
    title: "Latest News From NAR",
    slug: "latest-news-from-nar",
    excerpt: "https://www.nar.realtor/latest-news-from-nar",
    content:
      "<p>The latest macro housing economic insights and news highlights from the National Association of Realtors.</p><p>Comprehensive analysis of national inventory trends, buyer sentiment, regional sales statistics, and residential affordability metrics.</p>",
    sourceUrl: "https://www.nar.realtor/latest-news-from-nar",
    date: "December 26, 2025",
    category: "Market Trends",
    author: "Majeed",
    authorRole: "Principal Broker",
    readTime: "3 min read",
    coverImage: "/wp-content/themes/wpresidence/img/defaults/default_property_listings.jpg",
    tags: ["NAR", "News", "Market"],
    status: "Published",
    comments: 0,
    seoScore: 88,
    views: 0,
  },
  {
    id: "blog-8",
    title: "NAR Pending Home Sales Report Shows 1.9% Increase in October",
    slug: "32049-2",
    excerpt: "https://www.nar.realtor/newsroom/nar-pending-home-sales-report-shows-1-9-increase-in-october",
    content:
      "<p>The National Association of Realtors' Pending Home Sales Report recorded a <strong>1.9% increase</strong> in contract signings in October, reflecting robust homebuyer demand and strong transaction activity across the nation.</p><p>All four major U.S. regions posted month-over-month contract gains, signaling enduring momentum heading into the upcoming quarters.</p>",
    sourceUrl: "https://www.nar.realtor/newsroom/nar-pending-home-sales-report-shows-1-9-increase-in-october",
    date: "December 26, 2025",
    category: "Market Trends",
    author: "Majeed",
    authorRole: "Principal Broker",
    readTime: "3 min read",
    coverImage: "/wp-content/themes/wpresidence/img/defaults/default_property_listings.jpg",
    tags: ["NAR", "Sales Report", "Pending Sales"],
    status: "Published",
    comments: 0,
    seoScore: 91,
    views: 0,
  },
  {
    id: "blog-9",
    title: "SPLIT LEVEL HOME SOLD",
    slug: "split-level-home-sold",
    excerpt: "Sharif Realty Group celebrates another successful transaction of a turnkey split-level home.",
    content:
      "<p>Sharif Realty Group is proud to celebrate another successful residential closing with the sale of a turnkey split-level property.</p><p>Leveraging tailored presentation, targeted marketing, and focused buyer outreach, our team secured top market value for the sellers with seamless closing coordination. Contact our office to discover how we can achieve exceptional results for your property.</p>",
    date: "July 18, 2025",
    category: "Company News",
    author: "Majeed",
    authorRole: "Principal Broker",
    readTime: "2 min read",
    coverImage: "/wp-content/themes/wpresidence/img/defaults/default_property_listings.jpg",
    tags: ["Sold", "Success", "Residential"],
    status: "Published",
    comments: 0,
    seoScore: 93,
    views: 0,
  },
];

export const SEED_MEDIA_ASSETS_DATA: MediaAsset[] = ALL_PROPERTY_MEDIA_ASSETS;

export const SEED_CRM_LEADS_DATA: CrmLead[] = [
  {
    id: "LD-8492",
    name: "Eleanor Vance",
    email: "e.vance@hillhouse.com",
    phone: "(203) 555-0192",
    property: "Commercial Property At North Main St Waterbury",
    message: "Inquiring about commercial zoning and square footage availability for medical practice expansion.",
    status: "New",
    agent: "Majeed Sharif",
    date: "2026-08-26",
  },
  {
    id: "LD-8493",
    name: "Arthur Hastings",
    email: "hastings@stylescourt.org",
    phone: "(203) 555-0144",
    property: "Waterbury Connecticut",
    message: "Requesting private weekend showing for 2.1-acre estate parcel with pre-approved financing.",
    status: "In Progress",
    agent: "Majeed Sharif",
    date: "2026-08-25",
  },
  {
    id: "LD-8494",
    name: "Lucille Sharp",
    email: "lsharp@allerdale.co",
    phone: "(860) 555-0188",
    property: "Single family 4 bedrooms 3 baths",
    message: "Interested in full disclosure package and private inspection schedule.",
    status: "In Progress",
    agent: "Majeed Sharif",
    date: "2026-08-24",
  },
];
